# base image
FROM python:3.9-slim

# setup environment variable
ENV DockerHOME=/home/app/webapp

# set work directory
RUN mkdir -p $DockerHOME

# where your code lives
WORKDIR $DockerHOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip

# Install necessary system libraries
RUN apt-get update \
    && apt-get install -y gcc

# copy whole project to your docker home directory.
COPY ./requirements.txt $DockerHOME/requirements.txt
COPY ./sum_money.py $DockerHOME/sum_money.py

# run this command to install all dependencies
RUN pip install --no-cache-dir -r ./requirements.txt

# start server
CMD ["python", "sum_money.py"]

# To build -> docker build -t sum_money -f Dockerfile_sum_money .
# To run -> docker run sum_money