# base image
FROM python:3.11-slim

# setup environment variable
ENV DockerHOME=/home/app/webapp

# set work directory
RUN mkdir -p $DockerHOME

# where your code lives
WORKDIR $DockerHOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip

# Install necessary system libraries
RUN apt-get update

# copy whole project to your docker home directory.
COPY ./requirements.txt $DockerHOME/requirements.txt
COPY ./detect.py $DockerHOME/detect.py
COPY ./person.py $DockerHOME/person.py

# run this command to install all dependencies
RUN pip install --no-cache-dir -r ./requirements.txt

# start server
CMD ["python", "detect.py"]

# To build -> docker build -t detect -f Dockerfile_detect .
# To run -> docker run detect